### ISSUE TITLE
0.9.1 error in information

### ISSUE THREAD

**Issue by SergeyDjam** [tobimensch/aqemu#11]
![screen_259](https://cloud.githubusercontent.com/assets/11427162/15654343/0fa6aae0-269c-11e6-8ce3-1b4cf946558f.png)

This disk media device window

**Comment by tobimensch** [comment]
What's the real on disk size of the file? What file extension (qcow2, or vdi, or raw, or iso, etc.).

**Comment by SergeyDjam** [comment]
2Gb, raw img

**Comment by SergeyDjam** [comment]
Oh, delete and add this disk fix problem

**Comment by tobimensch** [comment]
Indeed, I can reproduce the problem with raw images.

For me newly created ones show up with 0GB.

So there's a bug, thanks for reporting.

Can you describe the exact steps that led to the info error?

Did you create the raw image with aqemu? (Or just add it)

**Comment by SergeyDjam** [comment]
I just added disk.

**Comment by tobimensch** [comment]
@SergeyDjam 

I just pushed a fix to git. Can you checkout master from
https://github.com/tobimensch/aqemu.git with git clone?

Or download this file to get https://github.com/tobimensch/aqemu/archive/master.zip
the latest changes.

Please do exactly the same as you did last time and tell me if there's
any difference.

Kind regards!

**Comment by tobimensch** [comment]
I just released a bug fix release with this fix.

https://github.com/tobimensch/aqemu/archive/v0.9.2.tar.gz

Can you try it and see if it's making any difference for you?

**Comment by SergeyDjam** [comment]
0.9.2 all ok

**Comment by tobimensch** [comment]
Awesome, thanks!
