### ISSUE TITLE
Reset / initial setup

### ISSUE THREAD

**Issue by jmbonet** [tobimensch/aqemu#14]
Hi. 

I think I've made a mistake when creating the inital setup. 

When I try to run aqemu I get somethink like this: 

AQEMU Debug [0] >>>
Sender: int main( int argc, char *argv[] )
Message: AQEMU Config Version: 0.8.1

AQEMU Debug [1] >>>
Sender: bool Emulator::Load( const QString &path )
Message: Loading emulator file version 0.8

AQEMU Debug [2] >>>
Sender: bool Emulator::Load( const QString &path )
Message: Loading emulator file version 0.8

AQEMU Warning [3] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu" element!

AQEMU Debug [4] >>>
Sender: bool Emulator::Load( const QString &path )
Message: Loading emulator file version 0.8

AQEMU Debug [5] >>>
Sender: bool Emulator::Load( const QString &path )
Message: Loading emulator file version 0.8

AQEMU Warning [6] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu" element!
Violació de segment (bolcat de la imatge del nucli)

Are there some way to redo the initial setup?

I've tried to uninstall and install again, but it seems that the setup remains and I have no idea where it is persisted.

**Comment by tobimensch** [comment]
try

rm -rf $HOME/.config/aqemu

What source did you install from?

**Comment by ford--prefect** [comment]
for me the config folder always lands in $HOME/.aqemu, nevertheless
.local is the better approach.
just in case you cant find it there

**Comment by tobimensch** [comment]
$HOME/.aqemu is the default folder for VMs, their images and configs.

However, $HOME/.config/aqemu is where the configuration of AQEMU itsself goes.

I think in your case @jmbonet you want to rm $HOME/.config/aqemu .

**Comment by tobimensch** [comment]
What version of AQEMU are you running?

**Comment by jmbonet** [comment]
Due the log messages, I guess the version is 0.8.1, but not sure.

There aren't any aqemu in .config nor in .local folders.

I have a empty .aqemu folder.

**Comment by tobimensch** [comment]
You must have used a source for installing, such as a distribution package, source package, or git.

What was your method of installing?

**Comment by jmbonet** [comment]
apt-get distribution package

**Comment by tobimensch** [comment]
http://unix.stackexchange.com/questions/6284/check-package-version-using-apt-get-aptitude

Try these:

apt-show-versions <package>

apt-cache policy <package>

**Comment by jmbonet** [comment]
aqemu:amd64/trusty 0.8.2-2

**Comment by tobimensch** [comment]
okay

0.8.2 is 5 years old. It's not supported anymore.

0.9.0, 0.9.1. and 0.9.2 were released this year.

Tell your distribution. :-)

**Comment by tobimensch** [comment]
You can also try to compile from source of course!

**Comment by jmbonet** [comment]
I'll try it, thank you ;)
