### ISSUE TITLE
"SPICE port number incorrect"

### ISSUE THREAD

**Issue by ford--prefect** [tobimensch/aqemu#2]
aqemu0.9 refuses to start a newly created virtual machine with the message "SPICE port number incorrect" despite SPICE not beeing turned on.

**Comment by tobimensch** [comment]
Can you attach the *.aqemu file that belongs to the VM which causes the issue? (In $HOME/.aqemu/)

I've seen the error, too, but only seldomly, and if I recall correctly it also happened with the old 0.8.2.

**Comment by ford--prefect** [comment]
github only likes a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP, so find it here: http://pastebin.com/Bsg2zzD5

**Comment by tobimensch** [comment]
I think the commit I just made might fix this as well. Worth a try. I've tried your file here and don't get the same error message. It just says "No boot image",  which is true, because I've no ARM image.

**Comment by ford--prefect** [comment]
i tried with the latest version from git (1caf23cf4508193a66511ba242b0e8884ecae29c) and still cannot save any changes on a newly created virtual machine. manually changing port numbers in .aqemu file did not yield any other result.

**Comment by tobimensch** [comment]
Ok, now that I started from a clean $HOME/.aqemu/ directory I can reproduce it. Will commit a fix soon.

**Comment by tobimensch** [comment]
Starting from a clean $HOME/.aqemu/ I get the same issue with aqemu 0.8.2 and master. So the good news seems to be that the issue isn't new.
The fix seems to be to create the first VM using the wizard. Following VMs can be created without it.

Can you verify that?

**Comment by tobimensch** [comment]
I just pushed a fix. Should fix this issue.

**Comment by ford--prefect** [comment]
I can confirm this fixes it for me (commit b023ccfd4ef13976df9b43d025800bea1206384a).
closing this.
