### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by DarylOliver** [tobimensch/aqemu#22]
Hello I'm having issues compiling I've tried compiling aqemu with command line and it errored about libvnc_liberies I used synaptic package manager and libvncclient1 is installed I then switched to the cmake gui then when I try to install debug mode no vnc support it doesn't generate libraries

if this is the incorrect package how do I find the right one also I can't seem to find how to install qemu 2.0.0 I'm running Ubuntu 16.04 64 bit and my cpu does support virtualisation.

any assistance in installing would be helpful thank you.

**Comment by tobimensch** [comment]
You don't need qemu 2.0.0, just any qemu version above 2.0. (even some versions below 2.0 might work)

If you get an error on the command line, please copy and paste the error right here.

Make sure development (dev/devel) packages for libvnc are installed as well. (don't know if that's really a requirement on ubuntu, but on a redhat based system it is)

**Comment by Aeirex** [comment]
@DarylOliver take a look here.
https://github.com/tobimensch/aqemu/issues/31

**Comment by DarylOliver** [comment]
@Aeirex Thank you this will help a lot aqemu is my prefered gui thanks for the help
