### ISSUE TITLE
Three Patches (Debian style)

### ISSUE THREAD

**Issue by runkharr** [tobimensch/aqemu#24]
I have three patches for you.
The first patch adds support for the discard option (enabling "thin provisioning").
The second adds the 'virtio scsi' interface type.
The third one adds the network interface type 'bridge' (including support for the helper program).

I created the patches against the current Debian version of AQEMU, so may be they may be not exactly matching the current HEAD in the GIT tree ...
[aqemu-patches.zip](https://github.com/tobimensch/aqemu/files/384239/aqemu-patches.zip)

**Comment by tobimensch** [comment]
I appreciate patches very much, of course it is always better if they are based on master.

It would be best if you could fork aqemu on github and make 3 pull requests (based on HEAD of master).

I will take close look at those patches in any case and likely apply them (it just makes a difference on how long I'll need to get it done).

Awesome work in any case, thanks.

**Comment by runkharr** [comment]
I know ...

I already created new patches (against the master/HEAD branch). If you want, i can send them, too. I even tested the result ... it works.

**Comment by tobimensch** [comment]
#26

**Comment by tobimensch** [comment]
@runkharr: This question is important: AQEMU is currently licensed under v2.0only of the GPL, so of course your patches are as well. However we/I may migrate AQEMU to v2.0+ or v2 and v3 of the GPL. Do you give permission to use your code under different FOSS licenses (such as GPLv3, whichever license we may decide on in the future, but of course never a proprietary license), too?

**Comment by runkharr** [comment]
This is ok for me. (== Approval granted.)
