### ISSUE TITLE
Feature request (Extra options input)

### ISSUE THREAD

**Issue by runkharr** [tobimensch/aqemu#25]
Please re-add the input box for adding options manually! I'm using some options (like "-balloon virtio") which (currently) can't be supplied in another way.

**Comment by tobimensch** [comment]
Not true. Click on "Advanced Options" in the upper right corner of the VM tab.

In the Advanced Options Dialog you can enter command line options as you wish.

**Comment by runkharr** [comment]
Ahh, thanks. I didn't see it ...
