### ISSUE TITLE
Replace Oxygen icons with Breeze icons

### ISSUE THREAD

**Issue by snassar** [tobimensch/aqemu#27]
aqemu is great. aqemu would be greater with Breeze icons.

Do you prefer PNG or can you work with SVG directly in the UI? I am happy to do a pull request for at least the icon references.

**Comment by tobimensch** [comment]
Currently the icons are practically hardcoded, we need to switch over to using the user's theme by default, and to only use the hardcoded icons as a fallback. That's a lot of easy but tedious work, and I don't think I'll get that done for the next release.

**Comment by snassar** [comment]
I am pretty good with easy and tedious. I am also pretty good with monkey-see-monkey-do. If you have an example of how it should be I am happy to replicate that.

**Comment by tobimensch** [comment]
you would need to make yourself familiar with the Qt API for Icons and its relationship with themes, and then you would also need to make yourself familiar with the AQEMU source code. I can't help too much as I currently have little time for AQEMU, which will hopefully change soon. Maybe I can work on it on the weekends.

**Comment by tobimensch** [comment]
@snassar 
Do you still have interest in this?

**Comment by snassar** [comment]
Hey @tobimensch , I wouldn't be able to commit the time. Sorry.
