### ISSUE TITLE
Close the app does not work

### ISSUE THREAD

**Issue by abucodonosor** [tobimensch/aqemu#3]
Hello,

first of all thx for doing the port..

I compiled aqemu against qt 5.6.0 and found out there is no way to 'close' the app. It dos not
work from File -> Exit nor directly from the window .. I have to kill it manually from console to close.

**Comment by abucodonosor** [comment]
Seems to only not work when no VM is added

**Comment by tobimensch** [comment]
Thanks for reporting that! Will be fixed.

**Comment by tobimensch** [comment]
This is fixed in git. Reopen this issue if there's any problem.
