### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Aeirex** [tobimensch/aqemu#31]
Using Ubuntu/Elementary 16.04. Not sure how to fix LIBVNCCLIENT_LIBRARIES.

```
seth@Elementary:~/Downloads/aqemu-0.9.2$ cmake -DCMAKE_INSTALL_PREFIX=/usr -DMAN_PAGE_COMPRESSOR=bzip2
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBVNCCLIENT_LIBRARIES
    linked by target "aqemu" in directory /home/seth/Downloads/aqemu-0.9.2

-- Configuring incomplete, errors occurred!
See also "/home/seth/Downloads/aqemu-0.9.2/CMakeFiles/CMakeOutput.log".
```

**Comment by tobimensch** [comment]
You have to install libvnc libraries. https://libvnc.github.io/
There are existing packages for it in ubuntu I suppose. An ubuntu forum would be the more appropriate place to ask for the right package name.

**Comment by Aeirex** [comment]
Thanks, you have to install developer packages to compile. Not the libraries. The confusing part is that, the compile guide doesn't let us know what we actually need - more or less just names. I can add a tutorial for Ubuntu users. @tobimensch 
https://github.com/LibVNC/libvncserver/issues/76
