### ISSUE TITLE
GCC 4.9 required ?

### ISSUE THREAD

**Issue by KaseiFR** [tobimensch/aqemu#32]
Hi,

I tried to build AQEMU 0.9.2 from the source tarball, and the linking at the end of the make fails with: http://pastebin.com/Tg0Wtyfp .
According to a quick search, GCC 4.8 does not support some required features to build the project: http://stackoverflow.com/a/8913707

I'm using GCC 4.8.4.

Do you think the README should be updated to specify GCC 4.9 as a requirement?

**Comment by tobimensch** [comment]
@KaseiFR 

You're right, the README should be updated and I will do it.
