### ISSUE TITLE
Failing to launch after upgrading libvncserver

### ISSUE THREAD

**Issue by tylerswagar** [tobimensch/aqemu#38]
Hello.  I'm not 100% that this isn't a distro-specific issue, but Arch doesn't appear to be applying any patches to AQEMU so I  have to assume this problem is upstream.  Upon upgrading to version 0.9.11 of libvncserver, AQEMU fails to launch.

`aqemu: error while loading shared libraries: libvncclient.so.0: cannot open shared object file: No such file or directory`

Downgrading to 0.9.10 fixes this for now, but of course that isn't ideal.  Then again, it's also possible that the latest libvncserver update is just botched in general, but I haven't seen anyone report an issue with any other application that depends on it.

Thank you.

**Comment by tobimensch** [comment]
Thanks for reporting this.

**Comment by tylerswagar** [comment]
Well, it turns out this whole time the solution was as simple as recompiling AQEMU.  So if anyone is having the same issue, just rebuild.

Sorry for the false alarm.
