### ISSUE TITLE
Slackware64 14.2

### ISSUE THREAD

**Issue by inukaze** [tobimensch/aqemu#39]
Hi there, how i can compile aqemu 0.9.2 under Slackware64 14.2 with the QT4 ???

Because its impossible for me compile QT5. i try 3 times, and after 8 hours of compilation of QT5 evers fails. i can't install QT5

a cause of that i need the Libs came with Slackware64 , the QT4.

**Comment by lefta** [comment]
AQemu uses QT5, their is no way to build it agaist QT4. If I'm right, the latest QT4 version is [0.8.2](https://sourceforge.net/projects/aqemu/files/aqemu/0.8.2/).

**Comment by rworkman** [comment]
You have to install qt5 - here's an option: https://slackbuilds.org/apps/qt5/

**Comment by tobimensch** [comment]
there will be no more Qt4 support for aqemu. It will probably get ported to Qt6, once that is released.
