### ISSUE TITLE
First start - UI is inconsistent between steps

### ISSUE THREAD

**Issue by mkrutov** [tobimensch/aqemu#62]
Screenshots with steps:

1) Open up AQemu first time. 

2) Click Next to "Find qemu" screen.
This:
https://i.imgur.com/FTd1kf9.png

3) Click next without searching.

4) Click back. This:
https://i.imgur.com/IynT6tR.png

This are two different UIs, which is not OK. In second UI (accessible via "back") buttons (both search, show all settings and select-file button) do nothing at all.

**Comment by tobimensch** [comment]
Well, I agree from your description of the issue, but the images you linked don't work anymore. I'm closing this, but keeping it in mind.

**Comment by mkrutov** [comment]
Interesting, because images are available for me. 
![one](https://user-images.githubusercontent.com/48674477/80705728-3638ec00-8ae7-11ea-8890-bdad32149f89.png)
![two](https://user-images.githubusercontent.com/48674477/80705730-36d18280-8ae7-11ea-8076-8ccc0ab7fedb.png)
