### ISSUE TITLE
Machine type

### ISSUE THREAD

**Issue by johndoe71rus** [tobimensch/aqemu#66]
HI. Can you explain the difference between the types of machines?
https://i.imgur.com/jsYejA2.jpg

**Comment by tobimensch** [comment]
No, the image you linked is not working anymore. I get a black image.

**Comment by johndoe71rus** [comment]
link work for me. Even firefox private mode(not in cache)

**Comment by tobimensch** [comment]
Sorry, the image blocker was unknowingly activated when I sent that comment. :-)
I can't really help you there, look up the documentation of QEMU, I think those types
are scraped directly from QEMUs output.
Is there something that doesn't work for you?

**Comment by johndoe71rus** [comment]
I usually used default. Perhaps these settings work. I do not understand how they differ. many identical names.
