### ISSUE TITLE
Error compiling with GCC 10

### ISSUE THREAD

**Issue by xsgordon** [tobimensch/aqemu#68]
I've been warned by the Fedora compiler team that aqemu will not build come the introduction of gcc-10 into the distribution.

> You're being contacted because a package you maintain in Fedora is going
to fail to build with gcc-10 in the spring.  Yes, I know that's many
months away, but it's far easier to fix this stuff proactively now than
wait.

> Fixing it now also means that your package will continue to be built
> with testing versions of gcc-10 as we proceed through the development
> process thus allowing additional issues to be caught early.
> 
> Your particular package will fail like this:
> 
> > BUILDSTDERR: In file included from /builddir/build/BUILD/aqemu-0.9.2/src/docopt/docopt.h:12,
> > BUILDSTDERR:                  from /builddir/build/BUILD/aqemu-0.9.2/src/docopt/docopt.cpp:9:
> > BUILDSTDERR: /builddir/build/BUILD/aqemu-0.9.2/src/docopt/docopt_value.h: In member function 'long int docopt::value::asLong() const':
> > BUILDSTDERR: /builddir/build/BUILD/aqemu-0.9.2/src/docopt/docopt_value.h:267:16: error: 'runtime_error' is not a member of 'std'
> > BUILDSTDERR:   267 |     throw std::runtime_error( str + " contains non-numeric characters.");
> 
> This is a relatively common failure we're seeing with gcc-10 and occurs
> as a result of header file cleanups within libstdc++.  For example
> various C++ runtime headers indirectly included <string> which in turn
> included <local> and <cerrno>.  Those indirect inclusions have been
> eliminated which in turn forces packages to include the C++ headers they
> actually need.

**Comment by tobimensch** [comment]
@xsgordon 
I accepted your pull request. Does this fix the issue?

**Comment by xsgordon** [comment]
Yes, thank you!
