### ISSUE TITLE
how to set resolution of VM?

### ISSUE THREAD

**Issue by excalibur1234** [tobimensch/aqemu#7]
i want to use aqemu as a replacement for virtualbox. so far, i can work around all the problems i have found (mentioned in issue #6 ), except for one: i cannot set the resolution of the VM.

these are the things i tried:
- re-sizing the aqemu window with the VM in it does not work. in virtualbox, i can enlarge the window with the VM in it and the resolution of the VM adapts to the new windows size. this is really comfortable. however, i do not expect this degree of comfort from aqemu.
- i have an OS (arch / manjaro linux) installed in my VM. i change the screen resolution from within that OS, but i can only lower it and not increase it!
- in aqemu GUI at the right hand side --> VM --> Options --> Fullscreen mode. when selected, this stretches the low resolution of my installed VM across my entire screen, but does not increase the screen resolution of my installed VM.
- in aqemu GUI at the right hand side --> Display --> QEMU Window --> initial graphical mode. this option seems the option i am looking for, but it is grayed out. i cannot use it. i have tried using different graphics cards in my VM, but this option stays grayed out.

if you are unclear of my descriptions, please tell me. i can provide screenshots...

**Comment by tobimensch** [comment]
This is an area where VirtualBox has an advantage, and is likely to keep its advantage in the mid term.

> re-sizing the aqemu window with the VM in it does not work. in virtualbox, i can enlarge the window with the VM in it and the resolution of the VM adapts to the new windows size. this is really comfortable. however, i do not expect this degree of comfort from aqemu.

It would be great if we could do this in AQEMU. VirtualBox has guest additions and the like to make such features seamless. Maybe it is possible to do it with aqemu/qemu, but not yet, as you found out.

> i have an OS (arch / manjaro linux) installed in my VM. i change the screen resolution from within that OS, but i can only lower it and not increase it!

Go to the "VM" tab and select a different Graphics card from the default one. They've different feature sets and strenghts/weaknesses. StdVGA, VM VMWare Graphics Card and qxl are worth a shot.

> in aqemu GUI at the right hand side --> Display --> QEMU Window --> initial graphical mode. this option seems the option i am looking for, but it is grayed out. i cannot use it. i have tried using different graphics cards in my VM, but this option stays grayed out.

That option is only available for Sparc32 emulation. I should make that clear in the GUI however.

I know about this issue, and will work to make this easier in future versions.

One way to work around it is to use either a SPICE client (best to set the graphics card to qxl when doing that!) or the embedded VNC window (File->Configure->User Interface->Embedded in VM Window).

I also had different results with different distributions and desktops.

I recommend trying the VMWare graphics card first, as it has a lot of features and is a good choice, although it also has a couple of bugs and required your guest OS to support it (many do).

**Comment by tobimensch** [comment]
Let me know if/how you could resolve the issue!

**Comment by tobimensch** [comment]
To quote the man page of qemu:
>            cirrus
               Cirrus Logic GD5446 Video card. All Windows versions starting
               from Windows 95 should recognize and use this graphic card. For
               optimal performances, use 16 bit color depth in the guest and
               the host OS.  (This one is the default)

>           std Standard VGA card with Bochs VBE extensions.  If your guest OS
               supports the VESA 2.0 VBE extensions (e.g. Windows XP) and if
               you want to use high resolution modes (>= 1280x1024x16) then
               you should use this option.

>           vmware
               VMWare SVGA-II compatible adapter. Use it if you have
               sufficiently recent XFree86/XOrg server or Windows guest with a
               driver for this card.

>           qxl QXL paravirtual graphic card.  It is VGA compatible (including
               VESA 2.0 VBE support).  Works best with qxl guest drivers
               installed though.  Recommended choice when using the spice
               protocol.

So:
 - cirrus is the default one used in AQEMU
 - std is StdVesa in AQEMU and should help to get higher resolutions
 - qxl is like std but with additional/better features
 - vmware is also worth a shot and most likely better than the default
 - cirrus/the default works with more systems out of the box however

Here is an interesting thread on how you can change the resolution in your guest
from the command line using the std/qxl driver:

**Comment by excalibur1234** [comment]
> Go to the "VM" tab and select a different Graphics card from the default one. They've different feature sets and strenghts/weaknesses. StdVGA, VM VMWare Graphics Card and qxl are worth a shot. If you choose qxl, install qxl drivers in your guest for best results. It also works without them, but then you don't get the advantages.
i just tried this with the same kind of success i had earlier: when using the tools for setting resolution within the installed VM, i can only lower the resolution, but not increase it.

> One way to work around it is to use either a SPICE client (best to set the graphics card to qxl when doing that!) 
i have tried this, but stopped when i noticed i need a separate program (SPICE client) to connect to my VM. this is not the solution i am looking for.

> or the embedded VNC window (File->Configure->User Interface->Embedded in VM Window).
this is neat. thanks for that tip! i have just tested this with all graphics options you recommended above (StdVGA, VM VMWare Graphics Card and qxl).but unfortunately, it does not solve my problem: i can only lower the resolution within the installed VM, but not increase it.


i am still testing. at the moment, i am trying different guest OSs. all previous tests were done with manjaro lxqt. i will report back soon.

**Comment by tobimensch** [comment]
I accidently edited your comment! I didn't even know this was possible on github. sorry!

**Comment by excalibur1234** [comment]
you were right.
when i used manjaro xfce and ubuntu as host OSs (in combination with the VMWare virtual graphics card), i could increase the resolution. in fact, ubuntu started in 4k resolution.
this solves this issue for me.

i have not tried xrandr/randr/arandr/lxrandr/kephal yet, but i will do that in the following days. if you are interested, i will give you some feedback when i am done.

when xrandr/randr/arandr/lxrandr/kephal work, then i start to use aqemu as a replacement for virtualbox. especially the virtualbox kernel driver is a constant source of annoyance for me.

**Comment by tobimensch** [comment]
> you were right. when i used manjaro xfce and ubuntu as host OSs (in combination with the VMWare virtual graphics card), i could increase the resolution. in fact, ubuntu started in 4k resolution.
this solves this issue for me.

Good!

> i have not tried xrandr/randr/arandr/lxrandr/kephal yet, but i will do that in the following days. if you are interested, i will give you some feedback when i am done.

I would love it! People that help testing software are invaluable in my opinion. Much appreciated!

> when xrandr/randr/arandr/lxrandr/kephal work, then i start to use aqemu as a replacement for virtualbox. especially the virtualbox kernel driver is a constant source of annoyance for me.

I'll wait for your report/findings. Agreed.

**Comment by excalibur1234** [comment]
in the last week i have installed 4 completely different manjaro versions: bspwm (very minimal), kde, lxqt, mate, xfce. 
somehow all of them were able to change the resolution. i am using the vmware video card. i also tested this before and was not able to change the resolution. this was the reason why i wrote this bug report.

this means, i did not have to test xrandr/randr/arandr/lxrandr/kephal. but almost everything is working now.

thanks a lot for your effort! i have removed virtualbox from my system a week ago.

**Comment by tobimensch** [comment]
@excalibur1234 Awesome! Keep an eye on this issue, and keep posting here, if you notice any other bugs/problems. Or if you have any other input/ideas/questions.

**Comment by Anyon3** [comment]
Hi,

I was wondering the same thing for a while and found the time today to study it.

I could definitively not make better than this anwser : 

http://superuser.com/a/971171

``` A simple resume

- StdVGA (VESA 2.0)

Once you got running your X env on aqemu/qemu, open a terminal (no need root permission, all can be entered in user) :

http://sprunge.us/FQOd

Hope it will help someone
