### ISSUE TITLE
Build Error with ubuntu 20.04

### ISSUE THREAD

**Issue by daleclack** [tobimensch/aqemu#77]
I tried build with ubuntu20.04,but I experienced an error:
The Meson build system
Version: 0.53.2
Source dir: /home/dale/aqemu
Build dir: /home/dale/aqemu/builddir
Build type: native build
Project name: aqemu
Project version: undefined
C++ compiler for the host machine: c++ (gcc 9.3.0 "c++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
WARNING: rcc dependencies will not work reliably until this upstream issue is fixed: https://bugreports.qt.io/browse/QTBUG-45460
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency qt5 (modules: Core, Gui, Widgets, Network, Test, PrintSupport, DBus) found: YES 5.12.8 (pkg-config)
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency libvncclient found: NO (tried pkgconfig and cmake)

meson.build:8:0: ERROR: Dependency "libvncclient" not found, tried pkgconfig and cmake

A full log can be found at /home/dale/aqemu/builddir/meson-logs/meson-log.txt
I tried install "libvncclient",but there is only libvncclient1 in ubuntu repository.

**Comment by tobimensch** [comment]
Did you try it with libvncclient1? Maybe also try libvncserver, if there's such a package.

**Comment by daleclack** [comment]
I installed libvncserver-dev,and the error disappeared. Thank you. :)
